config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  # resources :users

  # Admin namespace
  namespace :admin, path: 'admin' do
    resources :users
    resources :entities
    # Admin root path
    match '/', to: 'dashboard#index', via: [:get], as: :root
  end

  # SubAdmin namespace
  namespace :subadmin, path: 'sub' do
    resources :users
    # SubAdmin root path
    match '/', to: 'dashboard#index', via: [:get], as: :root
  end

  # Manager namespace
  namespace :manager, path: 'm' do
    # Manager root path
    match '/', to: 'dashboard#index', via: [:get], as: :root
  end

  # User namespace
  namespace :user, path: 'u' do
    # User root path
    match '/', to: 'dashboard#index', via: [:get], as: :root
  end

  # Guest namespace
  namespace :guest, path: 'g' do
    # Guest root path
    match '/', to: 'dashboard#index', via: [:get], as: :root
  end

end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_info.rb
class ContactInfo < ApplicationRecord
  belongs_to :address
  belongs_to :entity
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :contact_info
  belongs_to :address
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/mapping.rb
class Mapping < ApplicationRecord
  belongs_to :mapping_type
  belongs_to :group
end

app/models/mapping_type.rb
class MappingType < ApplicationRecord
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:guest, :user, :manager, :admin, :subadmin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  layout 'layouts/admin/users/users_layout'
  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to admin_users_path, :notice => "User updated."
    else
      redirect_to admin_users_path, :alert => "Unable to update user."
    end
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin

  private

  # Require an administrator role for being in this portal
  def require_admin
    unless current_user.admin?
      flash[:error] = "Not authorized for this portal!"
      redirect_to appropriate_redirect_url
    end
  end

end

app/controllers/entity_controller.rb
class EntityController < ApplicationController
end

app/controllers/guest_controller.rb
class GuestController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin

  private

  # Require an administrator role for being in this portal
  def require_admin
    unless current_user.guest?
      flash[:error] = "Not authorized for this portal!"
      redirect_to appropriate_redirect_url
    end
  end
end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin

  private

  # Require an administrator role for being in this portal
  def require_admin
    unless current_user.manager?
      flash[:error] = "Not authorized for this portal!"
      redirect_to appropriate_redirect_url
    end
  end
end

app/controllers/subadmin_controller.rb
class SubadminController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin

  private

  # Require an administrator role for being in this portal
  def require_admin
    unless current_user.subadmin?
      flash[:error] = "Not authorized for this portal!"
      redirect_to appropriate_redirect_url
    end
  end
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < UsersController
  layout 'layouts/user/dashboard/dashboard_layout'
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.user?
      redirect_to appropriate_redirect_url
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entity_helper.rb
module EntityHelper
end

app/helpers/guest_helper.rb
module GuestHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/subadmin_helper.rb
module SubadminHelper
end

app/helpers/user/dashboard_helper.rb
module User::DashboardHelper
end

app/views/layouts/admin/users/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', admin_root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/admin/dashboard/navigation_links'

app/views/layouts/admin/users/_navigation_links.html.haml
= render 'layouts/admin/dashboard/nav_links_for_auth'

app/views/layouts/admin/users/users_layout.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'User Starter'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'User Starter'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/admin/users/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = render 'layouts/admin/sidebar'
      #wrapper
        #page-content-wrapper
          .container-fluid
            .row
              .col-lg-12
                = yield
                %a#menu-toggle.btn.btn-default{:href => "#menu-toggle"} Toggle Menu
      -# Menu Toggle Script
      :javascript
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });